services:
  scheduler:
    image: ghcr.io/felipesanchezcla1/distriapp-crons:scheduler-latest
    container_name: scheduler
    env_file: .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    restart: unless-stopped